/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface HarbergerAdsFactoryInterface extends utils.Interface {
  functions: {
    "create(uint256,uint256,uint256,address,address,string)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "create"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "create",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;

  events: {
    "HarbergerAdsCreated(string,address,uint256,uint256,uint256,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HarbergerAdsCreated"): EventFragment;
}

export interface HarbergerAdsCreatedEventObject {
  _name: string;
  _address: string;
  _adCount: BigNumber;
  _taxRate: BigNumber;
  _cooldownPeriod: BigNumber;
  _currency: string;
  _collector: string;
}
export type HarbergerAdsCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string, string],
  HarbergerAdsCreatedEventObject
>;

export type HarbergerAdsCreatedEventFilter =
  TypedEventFilter<HarbergerAdsCreatedEvent>;

export interface HarbergerAdsFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HarbergerAdsFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    create(
      _adCount: PromiseOrValue<BigNumberish>,
      _taxRate: PromiseOrValue<BigNumberish>,
      _cooldownPeriod: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _collector: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  create(
    _adCount: PromiseOrValue<BigNumberish>,
    _taxRate: PromiseOrValue<BigNumberish>,
    _cooldownPeriod: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<string>,
    _collector: PromiseOrValue<string>,
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    create(
      _adCount: PromiseOrValue<BigNumberish>,
      _taxRate: PromiseOrValue<BigNumberish>,
      _cooldownPeriod: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _collector: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "HarbergerAdsCreated(string,address,uint256,uint256,uint256,address,address)"(
      _name?: PromiseOrValue<string> | null,
      _address?: null,
      _adCount?: null,
      _taxRate?: null,
      _cooldownPeriod?: null,
      _currency?: null,
      _collector?: null
    ): HarbergerAdsCreatedEventFilter;
    HarbergerAdsCreated(
      _name?: PromiseOrValue<string> | null,
      _address?: null,
      _adCount?: null,
      _taxRate?: null,
      _cooldownPeriod?: null,
      _currency?: null,
      _collector?: null
    ): HarbergerAdsCreatedEventFilter;
  };

  estimateGas: {
    create(
      _adCount: PromiseOrValue<BigNumberish>,
      _taxRate: PromiseOrValue<BigNumberish>,
      _cooldownPeriod: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _collector: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _adCount: PromiseOrValue<BigNumberish>,
      _taxRate: PromiseOrValue<BigNumberish>,
      _cooldownPeriod: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _collector: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
